name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20', '22']

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install, lint, and test
      run: |
        yarn install
        yarn lint
        yarn test --coverage
      env:
        CI: true
    - run: cat ${GITHUB_EVENT_PATH}
    - name: Upload coverage report
      run: |
        bash <(curl -s https://codecov.io/bash) \
          -t "${{ secrets.CODECOV_TOKEN }}" \
          -F node_${{ matrix.node-version }} \
          -B "${GITHUB_REF//refs\/heads\//}" \
          -T "${GITHUB_REF//refs\/tags\//}" \
          -C "$GITHUB_SHA"
